
#Configurations for material Eezo.
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = false
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "metallic"
	#The color of this material.
	color = 2434856

[molten]
	#The temperature of this molten fluid.
	temperature = 1000

[avaritia]
	#The base amount of blocks required to create one singularity.
	inputAmount = 300
	#Should the singularity be added to the Infinity Catalyst recipe.
	addToCatalyst = true

[enderio]
	#The default byproduct material to output in Ender IO's sagmill.
	byproduct = "minecraft:cobblestone"

[mekanism]
	#The default base to use in Mekanism's Combiner to recreate ores.
	oreBase = "minecraft:cobblestone"

[mysticalagriculture]
	#The crop tier of this material.
	tier = 3
	#The amount of Mystical Agriculture essence required to craft materials.
	inputCount = 8
	#The amount of material obtained by crafting Mystical Agriculture essence.
	outputCount = 4

[exnihilocreatio]
	#The default base to sieve in Ex Nihilo Creatio to get ore pieces.
	oreBase = "#crushedAndesite"
	#The output chance of the sieve recipes added using a flint mesh.
	sieveFlintChance = 0.05000000074505806
	#The output chance of the sieve recipes added using an iron mesh.
	sieveIronChance = 0.07500000298023224
	#The output chance of the sieve recipes added using a diamond mesh.
	sieveDiamondChance = 0.15000000596046448

[thermalexpansion_mysticalagriculture]
	#The base seed output chance when growing Mystical Agriculture seeds in Thermal Expansion's Insolator with Phyto-Gro.
	basicChance = 100
	#The base seed output chance when growing Mystical Agriculture seeds in Thermal Expansion's Insolator with Rich Phyto-Gro.
	richChance = 105
	#The base seed output chance when growing Mystical Agriculture seeds in Thermal Expansion's Insolator with Fluxed Phyto-Gro.
	fluxChance = 110

[magneticraft]
	#The default byproduct material to output in Magneticraft's grinder.
	grinderByproduct = "minecraft:gravel"
	#The default byproduct material to output in Magneticraft's sluice box.
	sluiceBoxByproduct = "minecraft:cobblestone"

